# Generated by Django 4.0 on 2021-12-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cient',
            new_name='Client',
        ),
    ]
